# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-19 21:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplititUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'SplititUser',
                'verbose_name_plural': 'SplititUser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
