# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('voucher_type', models.CharField(choices=[('P', 'PERCENTAGE'), ('FA', 'FIXED_AMOUNT'), ('E', 'EQUALLY')], default='E', max_length=50)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7)),
                ('name', models.CharField(blank=True, default='INR', max_length=100)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='GroupTransaction',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7)),
                ('debter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_debter', to='api.SplititUser')),
            ],
            options={
                'verbose_name': 'GroupTransaction',
                'verbose_name_plural': 'GroupTransaction',
            },
        ),
        migrations.CreateModel(
            name='SplititGroup',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('to_simplify', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='api.SplititUser')),
                ('members', models.ManyToManyField(blank=True, to='api.SplititUser')),
            ],
            options={
                'verbose_name': 'SplititGroup',
                'verbose_name_plural': 'SplititGroups',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bill')),
                ('debter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SplititUser')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bill',
            },
        ),
        migrations.AddField(
            model_name='grouptransaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SplititGroup'),
        ),
        migrations.AddField(
            model_name='grouptransaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payer', to='api.SplititUser'),
        ),
        migrations.AddField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SplititGroup'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SplititUser'),
        ),
    ]
