# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201220_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='voucher_type',
            new_name='splitting_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=100),
        ),
        migrations.AddField(
            model_name='splitituser',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
