# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-20 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201220_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptransaction',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_debtor', to='api.SplititUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SplititUser'),
        ),
    ]
