# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201220_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='splititgroup',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='splititgroup',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
