# Generated by Django 3.1.4 on 2020-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201221_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splititgroup',
            name='to_simplify',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
